import type { Project } from '@/lib/types'

export const projects: Project[] = [
  {
    slug:        'vr-haptic',
    key:         'KEY_01',
    serial:      'PRJ-RES-001',
    title:       'VR Haptic Research Platform',
    subtitle:    'Vibrotactile feedback in VR built environments',
    category:    'research',
    tags:        ['VR', 'Unity', 'C#', 'Haptics', 'HCI'],
    status:      'in-progress',
    date:        'MAR 2024',
    description: 'PhD research investigating vibrotactile feedback systems for spatial perception in virtual reality architectural walkthroughs. Explores embodied interaction at the intersection of built environments and immersive simulation. Pilot studies show statistically significant improvement in depth perception accuracy.',
    year:        2024,
  },
  {
    slug:        'robot-arm',
    key:         'KEY_02',
    serial:      'PRJ-ROB-002',
    title:       'Autonomous Robot Arm',
    subtitle:    '6-DOF pick-and-place system with ROS2',
    category:    'robotics',
    tags:        ['ROS2', 'Python', 'OpenCV', '3D Printing', 'C++'],
    status:      'active',
    date:        'JAN 2024',
    description: 'A 6-degree-of-freedom robotic arm with computer vision for autonomous pick-and-place operations. Implements inverse kinematics with real-time trajectory planning and object detection via OpenCV. Chassis fabricated with FDM 3D printing for rapid prototyping.',
    github:      'https://github.com/yourhandle/robot-arm',
    year:        2024,
  },
  {
    slug:        'iot-env',
    key:         'KEY_03',
    serial:      'PRJ-IOT-003',
    title:       'Smart Environment IoT',
    subtitle:    'Adaptive home automation mesh network',
    category:    'iot',
    tags:        ['ESP32', 'MQTT', 'Flutter', 'Firebase'],
    status:      'completed',
    date:        'NOV 2023',
    description: 'ESP32-based mesh network for smart home automation with ML-based context inference. Achieves sub-200ms response latency while reducing false-positive trigger rates by 62%. Paired with a cross-platform Flutter control app backed by Firebase real-time sync.',
    github:      'https://github.com/yourhandle/iot-env',
    year:        2023,
  },
  {
    slug:        'mobile-app',
    key:         'KEY_04',
    serial:      'PRJ-APP-004',
    title:       'Field Data Collector',
    subtitle:    'Cross-platform research data collection app',
    category:    'app',
    tags:        ['Flutter', 'Dart', 'SQLite', 'BLE'],
    status:      'completed',
    date:        'AUG 2023',
    description: 'A Flutter app for collecting structured research data in remote field environments. Features offline-first SQLite storage, BLE sensor pairing for wearable devices, and background data sync when connectivity is restored. Deployed across three independent research studies.',
    year:        2023,
  },
]

export const projectCategories = ['ALL', 'RESEARCH', 'ROBOTICS', 'IoT', 'APP'] as const
