import type { Project } from '@/lib/types'

export const projects: Project[] = [
  {
    slug:        'vr-haptic',
    key:         'KEY_01',
    title:       'VR Haptic Research',
    subtitle:    'Vibrotactile feedback in VR built environments',
    category:    'research',
    tags:        ['VR', 'Unity', 'C#', 'Haptics', 'HCI'],
    status:      'in-progress',
    description: 'PhD research investigating vibrotactile feedback systems for spatial perception in virtual reality.',
    year:        2024,
  },
  {
    slug:        'robot-arm',
    key:         'KEY_02',
    title:       'Autonomous Robot Arm',
    subtitle:    '6-DOF pick-and-place system with ROS2',
    category:    'robotics',
    tags:        ['ROS2', 'Python', 'OpenCV', '3D Printing', 'C++'],
    status:      'active',
    description: 'A 6-degree-of-freedom robot arm with computer vision for autonomous pick-and-place tasks.',
    github:      'https://github.com/yourhandle/robot-arm',
    year:        2024,
  },
  {
    slug:        'iot-env',
    key:         'KEY_03',
    title:       'Smart Environment IoT',
    subtitle:    'Home automation mesh network',
    category:    'iot',
    tags:        ['ESP32', 'MQTT', 'Flutter', 'Firebase'],
    status:      'completed',
    description: 'ESP32-based mesh network for smart home automation with a Flutter mobile app.',
    github:      'https://github.com/yourhandle/iot-env',
    year:        2023,
  },
  {
    slug:        'mobile-app',
    key:         'KEY_04',
    title:       'Field Data Collector',
    subtitle:    'Cross-platform research data collection app',
    category:    'app',
    tags:        ['Flutter', 'Dart', 'SQLite', 'BLE'],
    status:      'completed',
    description: 'A Flutter app for collecting structured research data in the field with offline sync.',
    year:        2023,
  },
]
